function [x_dot] = func_vehicle(x, u)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
theta_1 = x(3);

f_x = [0, 0, 0 ,cos(theta_1), 0;...
       0, 0, 0, sin(theta_1), 0;...
       0, 0, 0, 0 , 1;...
       0, 0, 0, 0, 0;...
       0, 0, 0, 0, 0];
g_x = [0, 0;...
       0, 0;...
       0, 0;...
       1, 0;...
       0, 1];

x_dot = f_x*x + g_x*u;
 
end